[project]
name = "mcp_crash_course"
version = "0.1.0"
description = "MCP Demo by Krish Naiak"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain>=1.2.10",
    "langchain-groq>=1.1.2",
    "langchain-openai>=1.1.9",
    "mcp[cli]>=1.26.0",
    "mcp-use>=1.2.6",
    "python-dotenv>=1.2.1",
    "asyncio>=4.0.0",
    "nest-asyncio>=1.6.0",
    "gradio[mcp]>=6.5.1",
]

